stages:
  - conventional-commits-linting
  - formatting
  - linting
  - compiling
  - unit-testing


conventional-commits-linting:
  stage: conventional-commits-linting
  image: rust
  before_script:
    - cargo install conventional_commits_linter
  script:
    - COMMON_ANCESTOR_COMMIT=`git merge-base origin/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME`
    # Lint all the commits in the branch.
    - /usr/local/cargo/bin/conventional_commits_linter --from-commit-hash $COMMON_ANCESTOR_COMMIT --allow-angular-type-only
  rules:
    - if: $CI_MERGE_REQUEST_ID


include:
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/check_permutation.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/is_unique.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/one_away.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/palindrome_permutation.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/rotate_matrix.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/string_compression.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/string_rotation.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/urlify.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/zero_matrix.yml
  - local: .gitlab/ci/factorial/common_lisp.yml
  - local: .gitlab/ci/fibonacci/common_lisp.yml
  - local: .gitlab/ci/largest_number/common_lisp.yml
  - local: .gitlab/ci/largest_number/rust.yml
  - local: .gitlab/ci/leetcode/7_reverse_integer/rust.yml
  - local: .gitlab/ci/leetcode/20_valid_parentheses/rust.yml
  - local: .gitlab/ci/leetcode/22_generate_parentheses/rust.yml
  - local: .gitlab/ci/leetcode/46_permutations/rust.yml
  - local: .gitlab/ci/leetcode/50_pow/rust.yml
  - local: .gitlab/ci/leetcode/76_minimum_window_substring/rust.yml
  - local: .gitlab/ci/leetcode/98_validate_binary_search_tree/rust.yml
  - local: .gitlab/ci/leetcode/139_word_break/rust.yml
  - local: .gitlab/ci/leetcode/165_compare_version_numbers/rust.yml
  - local: .gitlab/ci/leetcode/200_number_of_islands/rust.yml
  - local: .gitlab/ci/leetcode/206_reverse_linked_list/rust.yml
  - local: .gitlab/ci/leetcode/238_product_of_array_except_self/rust.yml
  - local: .gitlab/ci/leetcode/387_first_unique_character_in_a_string/rust.yml
  - local: .gitlab/ci/leetcode/543_diameter_of_binary_tree/rust.yml
  - local: .gitlab/ci/leetcode/819_most_common_word/rust.yml
  - local: .gitlab/ci/sum_list/common_lisp.yml
