stages:
  - clean-git-history-checking
  - conventional-commits-linting
  - formatting
  - linting
  - compiling
  - unit-testing


clean-git-history-checking:
  stage: clean-git-history-checking
  image: rust
  before_script:
    - cargo install clean_git_history
  script:
    # Check all the commits in the branch.
    - /usr/local/cargo/bin/clean_git_history --from-reference "origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
  rules:
    - if: $CI_MERGE_REQUEST_ID


conventional-commits-linting:
  stage: conventional-commits-linting
  image: rust
  before_script:
    - cargo install conventional_commits_linter
  script:
    # Lint all the commits in the branch.
    - /usr/local/cargo/bin/conventional_commits_linter --from-reference "origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}" --allow-angular-type-only
  rules:
    - if: $CI_MERGE_REQUEST_ID


include:
  - local: .gitlab/ci/advent_of_code/2021/day1/haskell.yml
  - local: .gitlab/ci/advent_of_code/2021/day2/haskell.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/check_permutation/rust.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/is_unique/rust.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/one_away/rust.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/palindrome_permutation/rust.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/rotate_matrix/rust.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/string_compression/rust.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/string_rotation/rust.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/urlify/rust.yml
  - local: .gitlab/ci/cracking_the_coding_interview/chapter_1_arrays_and_strings/zero_matrix/rust.yml
  - local: .gitlab/ci/factorial/common_lisp.yml
  - local: .gitlab/ci/fibonacci/common_lisp.yml
  - local: .gitlab/ci/largest_number/common_lisp.yml
  - local: .gitlab/ci/largest_number/rust.yml
  - local: .gitlab/ci/leetcode/7_reverse_integer/rust.yml
  - local: .gitlab/ci/leetcode/20_valid_parentheses/rust.yml
  - local: .gitlab/ci/leetcode/22_generate_parentheses/rust.yml
  - local: .gitlab/ci/leetcode/46_permutations/rust.yml
  - local: .gitlab/ci/leetcode/47_permutation_ii/rust.yml
  - local: .gitlab/ci/leetcode/50_pow/rust.yml
  - local: .gitlab/ci/leetcode/76_minimum_window_substring/rust.yml
  - local: .gitlab/ci/leetcode/78_subsets/rust.yml
  - local: .gitlab/ci/leetcode/88_merge_sorted_array/rust.yml
  - local: .gitlab/ci/leetcode/90_subsets_ii/rust.yml
  - local: .gitlab/ci/leetcode/98_validate_binary_search_tree/rust.yml
  - local: .gitlab/ci/leetcode/104_maximum_depth_of_binary_tree/rust.yml
  - local: .gitlab/ci/leetcode/111_minimum_depth_of_binary_tree/rust.yml
  - local: .gitlab/ci/leetcode/139_word_break/rust.yml
  - local: .gitlab/ci/leetcode/165_compare_version_numbers/rust.yml
  - local: .gitlab/ci/leetcode/200_number_of_islands/rust.yml
  - local: .gitlab/ci/leetcode/206_reverse_linked_list/rust.yml
  - local: .gitlab/ci/leetcode/226_invert_binary_tree/rust.yml
  - local: .gitlab/ci/leetcode/238_product_of_array_except_self/rust.yml
  - local: .gitlab/ci/leetcode/289_game_of_life/rust.yml
  - local: .gitlab/ci/leetcode/387_first_unique_character_in_a_string/rust.yml
  - local: .gitlab/ci/leetcode/543_diameter_of_binary_tree/rust.yml
  - local: .gitlab/ci/leetcode/700_search_in_a_binary_search_tree/rust.yml
  - local: .gitlab/ci/leetcode/701_insert_into_a_binary_search_tree/rust.yml
  - local: .gitlab/ci/leetcode/819_most_common_word/rust.yml
  - local: .gitlab/ci/leetcode/1091_shortest_path_in_binary_matrix/rust.yml
  - local: .gitlab/ci/leetcode/1102_path_with_maximum_minimum_value/rust.yml
  - local: .gitlab/ci/leetcode/1197_minimum_knight_moves/rust.yml
  - local: .gitlab/ci/leetcode/1299_replace_elements_with_greatest_element_on_right_side/rust.yml
  - local: .gitlab/ci/leetcode/1351_count_negative_numbers_in_a_sorted_matrix/rust.yml
  - local: .gitlab/ci/leetcode/1373_maximum_sum_bst_in_binary_tree/rust.yml
  - local: .gitlab/ci/leetcode/1382_balance_a_binary_search_tree/rust.yml
  - local: .gitlab/ci/leetcode/1429_first_unique_number/rust.yml
  - local: .gitlab/ci/leetcode/1431_kids_with_the_greatest_number_of_candies/rust.yml
  - local: .gitlab/ci/sum_list/common_lisp.yml
