VERSION 0.7


COPY_CI_DATA:
    COMMAND
    COPY --dir "ci/" "./"


COPY_SOURCECODE:
    COMMAND
    DO +COPY_CI_DATA
    COPY --dir "Day2.cabal" "src/" "tests/" "./"


haskell-base:
    FROM haskell:9.8.4@sha256:d71e0b4298d982ef469832cd3e62c9002356abbd0b407c939b1c06109d990c17
    RUN cabal update


haskell-formatting-base:
    FROM +haskell-base
    RUN cabal install ormolu
    DO +COPY_SOURCECODE


check-haskell-formatting:
    FROM +haskell-formatting-base
    RUN ./ci/check-haskell-formatting.sh


golang-base:
    FROM golang:1.24.0@sha256:3f7444391c51a11a039bf0359ee81cc64e663c17d787ad0e637a4de1a3f62a71


shell-formatting-base:
    FROM +golang-base
    RUN go install mvdan.cc/sh/v3/cmd/shfmt@v3.7.0
    DO +COPY_CI_DATA


check-shell-formatting:
    FROM +shell-formatting-base
    RUN ./ci/check-shell-formatting.sh


check-formatting:
    BUILD +check-haskell-formatting
    BUILD +check-shell-formatting


fix-haskell-formatting:
    FROM +haskell-formatting-base
    RUN ./ci/fix-haskell-formatting.sh
    SAVE ARTIFACT "src/" AS LOCAL "./"
    SAVE ARTIFACT "tests/" AS LOCAL "./"


fix-shell-formatting:
    FROM +shell-formatting-base
    RUN ./ci/fix-shell-formatting.sh
    SAVE ARTIFACT "ci/" AS LOCAL "./"


fix-formatting:
    BUILD +fix-haskell-formatting
    BUILD +fix-shell-formatting


check-haskell-linting:
    FROM +haskell-base
    RUN cabal install hlint
    DO +COPY_SOURCECODE
    RUN ./ci/check-haskell-linting.sh


ubuntu-base:
    FROM ubuntu:24.04@sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782
    # https://askubuntu.com/questions/462690/what-does-apt-get-fix-missing-do-and-when-is-it-useful
    RUN apt-get update --fix-missing


check-shell-linting:
    FROM +ubuntu-base
    RUN apt-get install shellcheck -y
    DO +COPY_CI_DATA
    RUN ./ci/check-shell-linting.sh


check-linting:
    BUILD +check-haskell-linting
    BUILD +check-shell-linting


compile:
    FROM +haskell-base
    DO +COPY_SOURCECODE
    RUN ./ci/compile.sh


unit-test:
    FROM +haskell-base
    DO +COPY_SOURCECODE
    RUN ./ci/unit-test.sh
