[package]
name = "one_away"
version = "0.1.0"
authors = ["C <DeveloperC@protonmail.com>"]
edition = "2021"


[dependencies]
log = "0.4.14"


[dev-dependencies]
pretty_env_logger = "0.4.0"
rstest = "0.6.4"
proptest = "1.0.0"
