[package]
name = "zero_matrix"
version = "0.1.0"
authors = ["C <DeveloperC@protonmail.com>"]
edition = "2021"


[dependencies]
# For matrix math/structs.
nalgebra = "0.33.0"


[dev-dependencies]
# For parameterized testing.
rstest = "=0.26.1"


[profile.release]
lto = 'fat'
codegen-units = 1
