[package]
name = "urlify"
version = "0.1.1"
authors = ["C <DeveloperC@protonmail.com>"]
edition = "2021"


[dependencies]


[dev-dependencies]
# For parameterized testing.
rstest = "=0.12.0"


[profile.release]
lto = 'fat'
codegen-units = 1
