VERSION 0.7


COPY_CI_DATA:
    COMMAND
    COPY --dir "ci/" "./"


COPY_SOURCECODE:
    COMMAND
    DO +COPY_CI_DATA
    COPY --dir "Day1.cabal" "src/" "tests/" "./"


haskell-base:
    FROM haskell:9.10.1@sha256:645497fa439e036f40a86f2af2e768037f162c5fb8504325b849287d76bbc10e
    RUN cabal update


haskell-formatting-base:
    FROM +haskell-base
    RUN cabal install ormolu
    DO +COPY_SOURCECODE


check-haskell-formatting:
    FROM +haskell-formatting-base
    RUN ./ci/check-haskell-formatting.sh


golang-base:
    FROM golang:1.24.2@sha256:991aa6a6e4431f2f01e869a812934bd60fbc87fb939e4a1ea54b8494ab9d2fc6


shell-formatting-base:
    FROM +golang-base
    RUN go install mvdan.cc/sh/v3/cmd/shfmt@v3.7.0
    DO +COPY_CI_DATA


check-shell-formatting:
    FROM +shell-formatting-base
    RUN ./ci/check-shell-formatting.sh


check-formatting:
    BUILD +check-haskell-formatting
    BUILD +check-shell-formatting


fix-haskell-formatting:
    FROM +haskell-formatting-base
    RUN ./ci/fix-haskell-formatting.sh
    SAVE ARTIFACT "src/" AS LOCAL "./"
    SAVE ARTIFACT "tests/" AS LOCAL "./"


fix-shell-formatting:
    FROM +shell-formatting-base
    RUN ./ci/fix-shell-formatting.sh
    SAVE ARTIFACT "ci/" AS LOCAL "./"


fix-formatting:
    BUILD +fix-haskell-formatting
    BUILD +fix-shell-formatting


check-haskell-linting:
    FROM +haskell-base
    RUN cabal install hlint
    DO +COPY_SOURCECODE
    RUN ./ci/check-haskell-linting.sh


ubuntu-base:
    FROM ubuntu:24.04@sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782
    # https://askubuntu.com/questions/462690/what-does-apt-get-fix-missing-do-and-when-is-it-useful
    RUN apt-get update --fix-missing


check-shell-linting:
    FROM +ubuntu-base
    RUN apt-get install shellcheck -y
    DO +COPY_CI_DATA
    RUN ./ci/check-shell-linting.sh


check-linting:
    BUILD +check-haskell-linting
    BUILD +check-shell-linting


compile:
    FROM +haskell-base
    DO +COPY_SOURCECODE
    RUN ./ci/compile.sh


unit-test:
    FROM +haskell-base
    DO +COPY_SOURCECODE
    RUN ./ci/unit-test.sh
